/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Faizul
 * Created: Oct 26, 2016
 */

CREATE TABLE ${dbschema}.SMSMSHIST (
    SMSMSHIST_ID NUMBER(32,0),
    SEND_IND VARCHAR(1) DEFAULT 'N',
    SMS_MESSAGE VARCHAR(1000),
    MOBILE_PHONE VARCHAR(20),
    FAIL_ACTION VARCHAR(2),
    SEND_COUNT NUMBER(12,0) DEFAULT 1, 
    PREV_UPDATED_DATETIME DATE,
    PREV_UPDATED_BY NUMBER(32,0),
    LAST_UPDATED_DATETIME DATE,
    LAST_UPDATED_BY NUMBER(32,0),
    ENTERED_BY NUMBER(32,0),
    ENTERED_DATETIME DATE
);

CREATE OR REPLACE PROCEDURE ${dbschema}.GET_UNSENDSMS(P_SMSMSHIST_ID IN NUMBER) 
BEGIN
    IF P_SMSMSHIST_ID IS NULL THEN
        SELECT SMSMSHIST_ID, MOBILE_PHONE, SMS_MESSAGE, FAIL_ACTION, SEND_COUNT FROM SMSMSHIST WHERE SEND_IND='N'
    ELSE
        SELECT MOBILE_PHONE, SMSMSHIST_MESSAGE, FAIL_ACTION, SEND_COUNT FROM SMSMSHIST WHERE SMSMSHIST_ID=P_SMSMSHIST_ID AND SEND_IND='N';
    END IF;
END;

CREATE OR REPLACE PROCEDURE ${dbschema}.GET_UPDATESMSHISTORY(P_SMSMSHIST_ID IN NUMBER) 
BEGIN
    UPDATE SMSMSHIST 
        SET SEND_IND='Y', 
            PREV_UPDATED_DATETIME=LAST_UPDATED_DATETIME, 
            PREV_UPDATED_BY=LAST_UPDATED_BY, 
            LAST_UPDATED_DATETIME=SYSDATE, 
            LAST_UPDATED_BY=ENTERED_BY WHERE SMSMSHIST_ID=P_SMSMSHIST_ID;
END;
